"""模块配置 Schema。"""

SCHEMA = {
    "enable_signin_command": {
        "type": "boolean",
        "label": "启用 #打卡 指令",
        "description": "允许通过 #打卡 指令为当前群打卡",
        "default": True,
    },
    "enable_all_signin_command": {
        "type": "boolean",
        "label": "启用 #全群打卡 指令",
        "description": "允许通过 #全群打卡 指令为所有已启用群打卡",
        "default": True,
    },
    "permission_scope": {
        "type": "select",
        "label": "指令权限范围(可能未实现)",
        "description": "谁可以使用打卡指令",
        "default": "bot_owner_only",
        "options": {
            "everyone": "所有人",
            "bot_owner_and_group_admin": "群主/管理员及以上",
            "bot_owner_only": "仅 Bot 拥有者",
        },
    },
    "enable_silence_signin": {
        "type": "boolean",
        "label": "静默模式",
        "description": "开启后打卡成功不回复消息（仅记录日志）",
        "default": True,
    },
    "enable_ignore_group_check": {
        "type": "boolean",
        "label": "忽略群列表检查",
        "description": "开启后任何群都可打卡（不校验下方群列表）",
        "default": False,
    },
    "group_mode": {
        "type": "select",
        "label": "打卡群范围",
        "description": "每日自动打卡覆盖的群范围",
        "default": "all",
        "options": {
            "all": "全部群",
            "partial": "仅勾选的群",
            "none": "不自动打卡",
        },
    },
    "group_configs": {
        "type": "list",
        "label": "打卡群列表",
        "description": "勾选参与打卡的群，按拖拽顺序执行；新群自动加入",
        "endpoint": "groups",
        "id_field": "group_id",
        "name_field": "group_name",
        "meta_fields": ["member_count"],
        "sortable": True,
        "checkboxes": True,
        "default": {},
    },
    "enable_daily_auto_signin": {
        "type": "boolean",
        "label": "启用每日自动打卡",
        "description": "每天在设定时间自动为所有已启用群打卡",
        "default": True,
    },
    "daily_signin_time": {
        "type": "time",
        "label": "自动打卡时间",
        "description": "每日自动打卡触发时间（修改后需刷新模块生效）",
        "default": "00:00",
    },
    "enable_custom_commands": {
        "type": "boolean",
        "label": "启用自定义指令",
        "description": "匹配用户配置的额外签到触发词",
        "default": False,
    },
    "custom_commands": {
        "type": "string_list",
        "label": "自定义触发词",
        "description": "输入不带前缀的词，如：签到、打卡啦",
        "default": [],
        "placeholder": "如：签到",
    },
    "enable_success_notify": {
        "type": "boolean",
        "label": "打卡成功通知",
        "description": "自动打卡完成后向配置的目标群/好友发送结果",
        "default": False,
    },
    "notify_groups": {
        "type": "list",
        "label": "通知群",
        "description": "接收打卡结果通知的群",
        "endpoint": "groups",
        "id_field": "group_id",
        "name_field": "group_name",
        "meta_fields": ["member_count"],
        "checkboxes": True,
        "default": {},
    },
    "notify_friends": {
        "type": "list",
        "label": "通知好友",
        "description": "接收打卡结果通知的好友",
        "endpoint": "friends",
        "id_field": "user_id",
        "name_field": "nickname",
        "checkboxes": True,
        "default": {},
    },
}
