"""插件系统：BaseModule / 注册表 / 权限 / 事件分发 / 插件 API。"""

from app.modules.api import (
    get_config_path,
    get_data_path,
    get_features,
    get_modules,
    register_daily_schedule,
)
from app.modules.authority import (
    PERMISSIONS,
    check_module_enabled,
    check_module_permission,
    compute_event_permission,
)
from app.modules.base import (
    BaseModule,
    ModuleAuthority,
    ModuleConfig,
    ModuleContext,
    ModulePermission,
    ServiceAccess,
    resolve_enabled_ids,
)
from app.modules.hooks import (
    ApiContext,
    ApiHookRegistry,
    BeforeSendContext,
    BeforeSendHookRegistry,
    EventCompletedContext,
    EventCompletedHookRegistry,
    LifecycleContext,
    LifecycleHookRegistry,
    SendContext,
    SendHookRegistry,
    api_hook,
    before_send_hook,
    bot_lifecycle_hook,
    event_completed_hook,
    llm_hook,
    module_hook,
    send_hook,
    tool_call_hook,
)
from app.modules.dispatcher import ModuleDispatcher
from app.modules.features import (
    AgentFeatureController,
    ConfigToggleFeature,
    FeatureController,
    FeatureLease,
    FeatureRegistry,
    KnowledgeFeatureController,
    MemoryFeatureController,
    NapcatToolsFeatureController,
    ProactiveFeatureController,
    ScheduleFeatureController,
)
from app.modules.keyword import match_keywords
from app.modules.registry import ModuleRegistry

__all__ = [
    "BaseModule",
    "ModuleAuthority",
    "ModuleConfig",
    "ModuleContext",
    "ModulePermission",
    "ServiceAccess",
    "ModuleRegistry",
    "ModuleDispatcher",
    "PERMISSIONS",
    "check_module_enabled",
    "check_module_permission",
    "compute_event_permission",
    "resolve_enabled_ids",
    "match_keywords",
    "FeatureRegistry",
    "FeatureController",
    "FeatureLease",
    "ConfigToggleFeature",
    "ProactiveFeatureController",
    "ScheduleFeatureController",
    "MemoryFeatureController",
    "KnowledgeFeatureController",
    "NapcatToolsFeatureController",
    "AgentFeatureController",
    "module_hook",
    "llm_hook",
    "send_hook",
    "SendContext",
    "SendHookRegistry",
    "before_send_hook",
    "BeforeSendContext",
    "BeforeSendHookRegistry",
    "api_hook",
    "ApiContext",
    "ApiHookRegistry",
    "bot_lifecycle_hook",
    "LifecycleContext",
    "LifecycleHookRegistry",
    "event_completed_hook",
    "EventCompletedContext",
    "EventCompletedHookRegistry",
    "tool_call_hook",
    # 插件 API
    "get_modules",
    "get_features",
    "get_config_path",
    "get_data_path",
    "register_daily_schedule",
]
