"""模块配置 Schema。"""

SCHEMA = {
    "enable_auto_parse": {
        "type": "boolean",
        "label": "启用自动解析",
        "description": "总开关：关闭后不解析任何 B 站链接",
        "default": True,
    },
    "enable_json_video": {
        "type": "boolean",
        "label": "解析小程序卡片",
        "description": "自动解析QQ内分享的B站小程序卡片",
        "default": True,
    },
    "enable_link_video": {
        "type": "boolean",
        "label": "解析链接",
        "description": "自动解析b23.tv短链和bilibili.com直链",
        "default": True,
    },
    "show_cover": {
        "type": "boolean",
        "label": "显示视频封面",
        "description": "在回复中显示视频封面图片",
        "default": True,
    },
    "max_parse_count": {
        "type": "integer",
        "label": "最大解析数量",
        "description": "单次消息中最多解析的视频数量",
        "default": 3,
        "min": 1,
        "max": 10,
    },
    "timeout": {
        "type": "integer",
        "label": "请求超时时长",
        "description": "API请求超时时间(秒)",
        "default": 10,
        "min": 5,
        "max": 30,
    },
    "cookie": {
        "type": "password",
        "label": "B站 Cookie（可选）",
        "description": "部分受限视频需要登录 Cookie 才能获取信息",
        "default": "",
    },
    "group_mode": {
        "type": "select",
        "label": "生效群范围",
        "description": "在哪些群中解析链接",
        "default": "all",
        "options": {
            "all": "全部群",
            "partial": "仅勾选的群",
            "none": "不解析",
        },
    },
    "group_configs": {
        "type": "list",
        "label": "生效群列表",
        "description": "勾选启用解析的群",
        "endpoint": "groups",
        "id_field": "group_id",
        "name_field": "group_name",
        "meta_fields": ["member_count"],
        "checkboxes": True,
        "mode_select": True,
        "default": {},
    },
    "is_reply": {
        "type": "boolean",
        "label": "引用原消息回复",
        "description": "仅「合并转发」关闭时生效：回复时引用触发的原消息",
        "default": True,
    },
    "use_forward_msg": {
        "type": "boolean",
        "label": "合并转发发送",
        "description": "开启：发一条合并转发（节点1 视频简介 / 节点2 720P 视频）；关闭：回落到旧版引用回复（不下载视频）",
        "default": True,
    },
    "enable_video_download": {
        "type": "boolean",
        "label": "下载并附带 720P 视频",
        "description": "取单文件流（音视频合一的 mp4，免 ffmpeg）并放进合并转发；只下载本次消息的第一个视频",
        "default": True,
        "showIf": {"key": "use_forward_msg", "value": True},
    },
    "video_quality": {
        "type": "select",
        "label": "视频清晰度",
        "description": "单文件模式实测匿名可达 720P（45MB / 2 分钟量级）；清晰度不足时按实际返回标注",
        "default": "720",
        "options": {"360": "360P 流畅", "480": "480P 清晰", "720": "720P 高清"},
        "showIf": {"key": "enable_video_download", "value": True},
    },
    "video_max_mb": {
        "type": "integer",
        "label": "视频体积上限 (MB)",
        "description": "超过上限则只发简介节点（附链接），避免超大投稿拖垮下载与上传",
        "default": 80,
        "min": 5,
        "max": 300,
        "showIf": {"key": "enable_video_download", "value": True},
    },
    "video_download_timeout": {
        "type": "integer",
        "label": "视频下载超时 (秒)",
        "description": "流式下载的单请求超时",
        "default": 60,
        "min": 10,
        "max": 300,
        "showIf": {"key": "enable_video_download", "value": True},
    },
    "video_cache_enabled": {
        "type": "boolean",
        "label": "复用本地视频缓存",
        "description": "同一视频只下载一次；缓存目录 module/data/bilibili_parser/video_cache",
        "default": True,
        "showIf": {"key": "enable_video_download", "value": True},
    },
    "video_cache_ttl_minutes": {
        "type": "integer",
        "label": "缓存保留时长 (分钟)",
        "description": "超过时长自动清理；0 表示不按时间淘汰",
        "default": 720,
        "min": 0,
        "max": 10080,
        "showIf": {"key": "video_cache_enabled", "value": True},
    },
    "video_cache_max_mb": {
        "type": "integer",
        "label": "缓存容量上限 (MB)",
        "description": "超出后删除最旧文件；0 表示不限制",
        "default": 1024,
        "min": 0,
        "max": 10240,
        "showIf": {"key": "video_cache_enabled", "value": True},
    },
    "enable_bv_dedup": {
        "type": "boolean",
        "label": "BV 去重",
        "description": "同一视频在超时时间内只解析一次，避免刷屏",
        "default": True,
    },
    "bv_dedup_timeout": {
        "type": "integer",
        "label": "去重时间（秒）",
        "description": "BV 去重缓存的有效时长",
        "default": 60,
        "min": 10,
        "max": 3600,
    },
}
