"""模块配置 Schema。"""

SCHEMA = {
    "cache_time": {
        "type": "number",
        "label": "内存缓存时间",
        "description": "撤回消息在内存中的缓存时间，单位秒（重启后由磁盘缓存兜底）",
        "default": 600,
        "placeholder": "输入缓存时间，单位秒",
    },
    "enable_group_listen": {
        "type": "boolean",
        "label": "监听群撤回",
        "description": "处理群聊撤回事件",
        "default": True,
    },
    "enable_private_listen": {
        "type": "boolean",
        "label": "监听私聊撤回",
        "description": "处理私聊撤回事件",
        "default": True,
    },
    "enable_forward_to_group": {
        "type": "boolean",
        "label": "转发到群聊",
        "description": "把撤回消息转发到目标群",
        "default": False,
    },
    "enable_forward_to_private": {
        "type": "boolean",
        "label": "转发到私聊",
        "description": "把撤回消息转发到目标好友",
        "default": False,
    },
    "target_groups": {
        "type": "list",
        "label": "目标群聊",
        "description": "撤回消息转发到的群（从群列表勾选）",
        "endpoint": "groups",
        "id_field": "group_id",
        "name_field": "group_name",
        "meta_fields": ["member_count"],
        "checkboxes": True,
        "mode_select": True,
        "default": {},
    },
    "target_users": {
        "type": "list",
        "label": "目标用户",
        "description": "撤回消息转发到的用户（从好友列表勾选）",
        "endpoint": "friends",
        "id_field": "user_id",
        "name_field": "nickname",
        "checkboxes": True,
        "mode_select": True,
        "default": {},
    },
    "db_enable": {
        "type": "boolean",
        "label": "启用持久化缓存",
        "description": "撤回消息落盘保存（module/data/notice_recall_back/），重启后仍可恢复",
        "default": True,
    },
    "db_max_messages": {
        "type": "integer",
        "label": "缓存总量上限（条）",
        "description": "超过上限后自动淘汰最旧的消息",
        "default": 5000,
        "min": 100,
    },
    "db_max_per_group": {
        "type": "integer",
        "label": "单群缓存上限（条）",
        "description": "每个群最多缓存的撤回消息数，超出淘汰该群最旧",
        "default": 200,
        "min": 10,
    },
    "db_retention_minutes": {
        "type": "integer",
        "label": "缓存保留时长（分钟）",
        "description": "超过保留时长的消息自动清理",
        "default": 60,
        "min": 1,
    },
    "db_clean_interval_minutes": {
        "type": "integer",
        "label": "自动清理间隔（分钟）",
        "description": "运行中周期清理过期/超量缓存的间隔",
        "default": 60,
        "min": 5,
    },
}
